apiVersion: prio.isrg-prio.org/v1
kind: Locality
metadata:
  name: narnia-locality
  namespace: narnia
spec:
  environmentName: narnia
  manifestBucketLocation: prio-amir-d2-manifests
  dataShareProcessors:
    - apple
    - google
  schedule: 0 5 * * 0
