[package]
name = "facilitator"
version = "0.1.0"
authors = ["Internet Security Research Group"]
edition = "2018"

[dependencies]
async-trait = "0.1"
anyhow = "1.0"
avro-rs = { version = "0.11.0", features = ["snappy"] }
base64 = "0.12.3"
chrono = { version ="0.4", features = ["serde"] }
clap = "2.33.3"
derivative = "2.1.1"
hyper = "0.13.8"
hyper-rustls = "0.21.0"
jsonwebtoken = "7"
log = "0.4.11"
once_cell = "1.4"
pem = "0.8"
prio = "0.2"
prometheus = { version = "0.10", features = [ "push" ] }
rand = "0.7"
regex = "1.4"
ring = { version = "0.16.15", features = ["std"] }
rusoto_core = { version = "0.45.0", default_features = false, features = ["rustls"] }
rusoto_s3 = { version = "0.45.0", default_features = false, features = ["rustls"] }
rusoto_sts = { version = "0.45.0", default_features = false, features = ["rustls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
env_logger = "0.8.1"
structopt = "0.3"
tempfile = "3.1.0"
thiserror = "1.0"
tokio = { version = "0.2", features = ["rt-core", "io-util"] }
ureq = { version = "1.5.2", features = ["json"] }
urlencoding = "1.1.1"
uuid = { version = "0.8", features = ["serde", "v4"] }

[dev-dependencies]
assert_matches = "1.4.0"
mockito = "0.27.0"
rusoto_mock = { version = "0.45.0", default_features = false, features = ["rustls"] }
serde_test = "1.0"
