[package]
name = "facilitator"
version = "0.1.0"
authors = ["Tim Geoghegan <timg@letsencrypt.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
avro-rs = "0.11.0"
libprio-rs = { git = "https://github.com/abetterinternet/libprio-rs"}
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "0.8", features = ["serde", "v4"] }
