[package]
authors = ["Internet Security Research Group"]
edition = "2018"
name = "facilitator"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
avro-rs = { version = "0.13.0", features = ["snappy"] }
base64 = "0.13.0"
chrono = { version = "0.4", features = ["serde"] }
clap = "2.33.3"
derivative = "2.1.1"
elliptic-curve = { version = "0.9.4", features = ["pem"] }
env_logger = "0.8.3"
http = "^0.2"
hyper = "^0.14"
hyper-rustls = "^0.22"
jsonwebtoken = "7"
k8s-openapi = { version = "0.11.0", default-features = false, features = ["v1_20"] }
kube = "0.51.0"
kube-runtime = "0.51.0"
log = "0.4.11"
p256 = "0.8.0-pre"
pem = "0.8"
pkix = "0.1.1"
prio = "0.3"
prometheus = "0.12"
rand = "0.8"
ring = { version = "0.16.20", features = ["std"] }
rusoto_core = { version = "^0.46", default_features = false, features = ["rustls"] }
rusoto_mock = { version = "^0.46", default_features = false, features = ["rustls"] }
rusoto_s3 = { version = "^0.46", default_features = false, features = ["rustls"] }
rusoto_sqs = { version = "^0.46", default_features = false, features = ["rustls"] }
rusoto_sts = { version = "^0.46", default_features = false, features = ["rustls"] }
serde = { version = "^1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3.1.0"
thiserror = "1.0"
tokio = { version = "^1.3", features = ["full"] }
ureq = { version = "^2.0", features = ["json"] }
url = "2.2.1"
urlencoding = "1.1.1"
uuid = { version = "0.8", features = ["serde", "v4"] }
warp = "^0.3"

[dev-dependencies]
assert_matches = "1.5.0"
mockito = "0.29.0"
serde_test = "1.0"
