[package]
name = "facilitator"
version = "0.1.0"
authors = ["Internet Security Research Group"]
edition = "2018"
build = "build.rs"

[dependencies]
anyhow = "1.0"
avro-rs = { version = "0.11.0", features = ["snappy"] }
base64 = "0.12.3"
chrono = "0.4"
clap = "2.33.3"
derivative = "2.1.1"
hyper = "0.13.8"
hyper-rustls = "0.21.0"
once_cell = "1.4"
pem = "0.8"
prio = "0.2"
rand = "0.7"
regex = "1.4"
ring = { version = "0.16.15", features = ["std"] }
rusoto_core = { version = "0.45.0", default_features = false, features = ["rustls"] }
rusoto_s3 = { version = "0.45.0", default_features = false, features = ["rustls"] }
rusoto_sts = { version = "0.45.0", default_features = false, features = ["rustls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3"
tempfile = "3.1.0"
thiserror = "1.0"
tokio = { version = "0.2", features = ["rt-core", "io-util"] }
ureq = "1.5.1"
uuid = { version = "0.8", features = ["serde", "v4"] }

[build-dependencies]
vergen = "3"

[dev-dependencies]
assert_matches = "1.4.0"
rusoto_mock = { version = "0.45.0", default_features = false, features = ["rustls"] }
serde_test = "1.0"
