apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.1.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: key-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: TerraformData is the Schema for the terraformdata API
      displayName: Terraform Data
      kind: TerraformData
      name: terraformdata.terraform.isrg-prio.com
      version: v1
  description: KeyOperator description
  displayName: keyoperator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - secret
          verbs:
          - create
          - get
          - patch
        - apiGroups:
          - terraform.isrg-prio.com
          resources:
          - terraformdata
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - terraform.isrg-prio.com
          resources:
          - terraformdata/status
          verbs:
          - get
          - patch
          - update
        serviceAccountName: default
      deployments:
      - name: key-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --enable-leader-election
                command:
                - /manager
                env:
                - name: MY_POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                image: us.gcr.io/prio-bringup-290620/keyoperator:latest
                name: manager
                resources:
                  limits:
                    cpu: 100m
                    memory: 30Mi
                  requests:
                    cpu: 100m
                    memory: 20Mi
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - configmaps/status
          verbs:
          - get
          - update
          - patch
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: default
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - keyoperator
  links:
  - name: Key Operator
    url: https://key-operator.domain
  maintainers:
  - email: "No"
    name: "No"
  maturity: alpha
  provider:
    name: KeyOperator Provider
    url: "No"
  version: 0.0.1
