apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.1.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: key-operator.vX.Y.Z
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: TerraformData is the Schema for the terraformdata API
      displayName: Terraform Data
      kind: TerraformData
      name: terraformdata.terraform.isrg-prio.com
      version: v1
  description: KeyOperator description
  displayName: keyoperator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - keyoperator
  links:
  - name: Key Operator
    url: https://key-operator.domain
  maintainers:
  - email: "No"
    name: "No"
  maturity: alpha
  provider:
    name: KeyOperator Provider
    url: "No"
  version: 0.0.0
