# DNS provider settings
[dns]
provider = "cloudflare" # options: cloudflare,

[dns.cloudflare]
api_key = "API_KEY"

[dns.gcp]
project = "project"

[dns.gcp.zone_mapping]
"certmagic_zone" = "gcp_zone"

# ACME settings
[acme]
email = "test@example.com"
acme_api_endpoint = "https://acme-staging-v02.api.letsencrypt.org/directory"
subscriber_agreement = false

[storage]
driver = "kubernetes" # options: kubernetes, filesystem,

[storage.filesystem]
path = "./deploy_tool_output"

[storage.kubernetes]
namespace = "prio-server"

[job]
enable = false # Enable this to run in `job` mode

[[job.jobs]]
name = "some_name" # Name of the job - will be used for printing/debugging
pha_name = "some-pha-name" # Name to be used in the manifest wrapper for gsutil
fqdn = "FQDN of pha_name" # FQDN of the pha_name
private_key_path = "path/to/private/key" # path to the private key of the job
