name: facilitator-ci-build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-rust:
    defaults:
      run:
        working-directory: facilitator
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint
      run: cargo fmt --message-format human -- --check
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  terraform:
    defaults:
      run:
        working-directory: terraform
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1
    - name: Terraform fmt
      run: terraform fmt -check -recursive
    - name: Terraform init
      run: terraform init --backend=false
    - name: Terraform validate
      run: terraform validate

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker build
      uses: docker/setup-buildx-action@v1
    - name: build
      uses: docker/build-push-action@v2
      with:
        file: ./facilitator/Dockerfile
