name: ci-build

on:
  push:
    branches: [ main, release/** ]
  pull_request:
    branches: [ main, release/** ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  facilitator-build:
    defaults:
      run:
        working-directory: facilitator
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint
      run: cargo fmt --message-format human -- --check
    - uses: actions-rs/clippy-check@v1
      with:
        # https://docs.github.com/actions/reference/authentication-in-a-workflow
        token: ${{ secrets.GITHUB_TOKEN }}
        # working-directory only applies to run actions, so path to Cargo.toml needs to be manually specified
        args: --manifest-path facilitator/Cargo.toml --all-targets
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  facilitator-coverage:
    defaults:
      run:
        working-directory: facilitator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install lcov
        run: sudo apt install lcov -y
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly # We have to use nightly for the coverage reports to be generated https://github.com/actions-rs/grcov#usage
          override: true
          default: true
      - name: Install grcov
        run: cargo install grcov
      - name: Test
        run: cargo test --all-features --no-fail-fast
        env:
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
          RUSTDOCFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
      - name: Get code coverage
        run: grcov ./target/debug -s . --llvm --branch --guess-directory-when-missing --ignore-not-existing -t lcov -o coverage.txt
      - name: Clean lcov file
        run: lcov --extract coverage.txt -o coverage.txt 'src/*'
      - name: Upload test coverage
        if: success()
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: false
          file: ./facilitator/coverage.txt
          flags: facilitator_tests
          name: facilitator tests

  terraform:
    defaults:
      run:
        working-directory: terraform
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1
    - name: Terraform fmt
      run: terraform fmt --check --recursive
    - name: Terraform init
      run: terraform init --backend=false
    - name: Terraform validate
      run: terraform validate

  facilitator-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker build
      uses: docker/setup-buildx-action@v1
    - name: build
      uses: docker/build-push-action@v2
      with:
        file: ./facilitator/Dockerfile

  deploy-operator-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker build
      uses: docker/setup-buildx-action@v1
    - name: build
      uses: docker/build-push-action@v2
      with:
        file: ./deploy-operator/Dockerfile
        context: ./deploy-operator

  manifest-updater-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker build
      uses: docker/setup-buildx-action@v1
    - name: build
      uses: docker/build-push-action@v2
      with:
        file: ./manifest-updater/Dockerfile
        context: ./manifest-updater