name: push-docker-image

on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Set up Docker build
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: isrgautomaton
        password: ${{ secrets.ISRG_AUTOMATON_DOCKERHUB_AUTH_TOKEN }}
    - name: build
      uses: docker/build-push-action@v2
      with:
        file: ./facilitator/Dockerfile
        push: true
        tags: letsencrypt/prio-facilitator:${{ steps.get_version.outputs.VERSION }}
